### PR TITLE
Fixing issues with the OWM weather service after their recent changes…

### LINKED ISSUE #122: Open weather map (OWM) free API changes break the weather service
It looks like at some point the OWM service changed the available API calls for their "free" tier subscription.  I've added a pull request which seems to work to fix the issue.  I mainly tried to just translate between the old API structure and the new one to keep the main code the same.  

The main area of concern would be the data aggregating I'm doing when translating between hourly forecasts and the previous 3 hour forecast data, should be minimal though.

### PR DESCRIPTION
**Pull request by cubiczar**
… to the free API. Resolves #122

### CODE REVIEW

**Comment by garudaonekh** [comment]
No, it's not working. 
Your code still referring the the subscription API.

`public async getWeatherData(coordinates: GeoCoordinates): Promise<WeatherData>  ---> throw "An error occurred while retrieving weather information from OWM."`

**Comment by garudaonekh** [comment]
It looks to be working fine for me.

**Review by salbahra — APPROVED** [review]
Apologies for the delay but approved!

**Comment by cubiczar** [comment]
No worries, life happens, just glad to be able to contribute.

**Pull request merged**
