### PR TITLE
Finish up pws endpoint

### PR DESCRIPTION
**Pull request by PeteBa**
Setting out use-cases and instructions.
Hardening code.

### CODE REVIEW

**Comment by salbahra** [comment]
I want to merge #22 and this will conflict with it. Do you mind reviewing #22 and rebasing the code changes here on that?

**Comment by PeteBa** [comment]
Totally fine, the last thing #22 needs is another rebase !

**Comment by salbahra** [comment]
We have merged in #22 now. If you don't mind rebasing this PR we can get it merged in.

Thanks!

**Comment by PeteBa** [comment]
Stripped back to just documentation updates. The #22 refactor sorted the rest.

**Pull request merged**
