### PR TITLE
Add mock WeatherProvider

### PR DESCRIPTION
**Pull request by Derpthemeus**
This will allow us to write tests that decouple adjustment method logic from WeatherProvider logic.

### CODE REVIEW

**Comment by salbahra** [comment]
Instead of putting this along side our other providers, could we put this inside of `.spec.ts` file? That way it's only used for testing purposes? Or do we need it to run as a module?

**Comment by Derpthemeus** [comment]
Sure, I'll move it into weather.spec.ts

**Comment by PeteBa** [comment]
Does this allow for mocking just one return value. I would want to be able to supply an array of observations that the mock iterates along with each call e.g. a day's worth of weather data. I can look at this as a separate PR if not in scope here.

**Comment by Derpthemeus** [comment]
It only allows you to specify a single return value for each method (`getWeatherData` and `getWateringData`) and that data will be returned regardless of the current data or coordinates specified. If you want to use multiple pairs of times and coordinates, you can make a new WeatherProvider for each one

**Comment by salbahra** [comment]
Do you mind resolving the merge conflict? I can merge this is once that's done.

**Pull request merged**
