### PR TITLE
Refactor codebase to TypeScript

### PR DESCRIPTION
**Pull request by Derpthemeus**

### CODE REVIEW

**Comment by Derpthemeus** [comment]
@PeteBa Would you mind making sure it looks like the local weather feature was merged correctly in 31e7e54 ?

**Comment by PeteBa** [comment]
@Derpthemeus , so I got a bit sidetracked 8) , and see that this has been merged in. I think it is a great job here. Only question I had was whether we need the ```filter.pws``` and ```filter.gps``` [here](https://github.com/OpenSprinkler/OpenSprinkler-Weather/blob/57e726da3e51b7fca1f519f10546ad16a816c950/routes/weather.ts#L257) as this should be handled by ```resolveCoordinates()``` ?

**Comment by Derpthemeus** [comment]
Good catch, the `filter.gps` check can indeed be removed (the `filter.pws` check is still necessary to provide a descriptive error message indicating PWS support was removed). I'll take that out in a bit when I get a chance

**Comment by PeteBa** [comment]
Or for ```fliter.pws``` you could change the equivalent error message [here](https://github.com/OpenSprinkler/OpenSprinkler-Weather/blob/57e726da3e51b7fca1f519f10546ad16a816c950/routes/weather.ts#L30) in ```resolveCoordinate()``` as it would be more applicable.

**Comment by Derpthemeus** [comment]
Great idea, I'll do that

**Comment by PeteBa** [comment]
One simplification for ```server.js``` but well beyond the scope of this PR 8) is to move the ```dotenv.config()``` line to before the declaration of ```host``` and ```port``` that way you can remove the whole if statement on line 16.

Dotenv default precedence is: environment variable -> .env file -> default value.

This one has bugged me for ages 8)

**Comment by salbahra** [comment]
Ah good to know! I’ll fix this thanks!

**Comment by PeteBa** [comment]
@Derpthemeus , OK, so had a chance to take a slower read through ```weather.ts```, three small code simplifications:

Change L134-137:
```
		let temp = wateringData.temp,
			humidityFactor = ( humidityBase - wateringData.humidity ),
			tempFactor = ( ( temp - tempBase ) * 4 ),
			precipFactor = ( ( precipBase - wateringData.precip ) * 200 );
```

To:
```
		let humidityFactor = ( humidityBase - wateringData.humidity ),
			tempFactor = ( ( wateringData.temp - tempBase ) * 4 ),
			precipFactor = ( ( precipBase - wateringData.precip ) * 200 );
```

L294-295: Stale comments

L297-306: I can't work out this piece of logic. It seems not to relate to the opening comments but if PWS identifiers are re-instated then they should be dealt with in ```resolveCoordinates()``` not elsewhere in the code.

Finally, L155, I think a conservative approach would use ```Math.ceil()``` given that this is about watering plants and a bit more is better than a bit less. 8)

Anyway, I had some other thoughts but there more around refactoring so let me know if your interested but right now it's past midnight in London. Again, great work,

**Pull request merged**
